version: 2.1
jobs:
  build:
    docker:
      - image: node:18.16.0
    environment:
      - BROWSERSTACK_USERNAME: ${browserstack_access_key}
      - BROWSERSTACK_ACCESS_KEY: ${browserstack_username}
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run WebdriverIO Tests
          command: npx wdio run ./android.browserstack.conf.ts

workflows:
  version: 2
  build-test:
    jobs:
      - build
      