name: CI
on: [push, pull_request]
jobs:
  build:
    env:
      BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
      BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm install
      - name: Run WebDriverIO
        run: npx wdio run ./android.browserstack.conf.ts
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs